euromammals/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.views.i18n import JavaScriptCatalog
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
import website.views as wviews

js_info_dict = {
   'domain': 'django',
   'packages': None,
}

urlpatterns = [
    path("mammalsadmin/", admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path("", wviews.homepage),
    path("contact/", wviews.contact_view),
    path("mailinglists/", wviews.mailing),
    path("logos/", wviews.logos),
    path("events/", wviews.events),
    path("event/<int:idd>/", wviews.event),
    path("pagers/", wviews.pagers),
    path("pubs/", wviews.publications),
    path("education/", wviews.educational),
    path("database/", wviews.database),
    path("euroboar/", wviews.project, {"projct": "EUROBOAR"}),
    path("eurolynx/", wviews.project, {"projct": "EUROLYNX"}),
    path("eurosmallmammals/", wviews.project, {"projct": "EUROSMALLMAMMALS"}),
    path("eurowildcat/", wviews.project, {"projct": "EUROWILDCAT"}),
    path("eurodeer/", wviews.project, {"projct": "EURODEER"}),
    path("eureddeer/", wviews.project, {"projct": "EUREDDEER"}),
    path("euroibex/", wviews.project, {"projct": "EUROIBEX"}),
    path("eurojackal/", wviews.project, {"projct": "EUROJACKAL"}),
    path("afrimove/", wviews.project, {"projct": "AfriMove"}),
    path("euroraccoon/", wviews.project, {"projct": "EURORACCOON"}),
    path('i18n/', include('django.conf.urls.i18n')),
    path('jsi18n/', JavaScriptCatalog.as_view(), js_info_dict,
         name='javascript_catalog'),
    path('captcha/', include('captcha.urls')),
    path("termofuse/", wviews.term_of_use),
] + static(settings.STATIC_URL,
           document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

events/models.py
from django.db import models
from django.utils.encoding import smart_str
from django.utils.translation import gettext_lazy as _

from core.models import Project
from core.models import User

# Create your models here.
EVENT_TYPE = (
    ('ME', _('Meeting')), ('CO', _('Conference')),
    ('SS', _('Summer school')), ('WO', _('Workshop')),
    ('TV', _('TV show')),
)

class Event(models.Model):
    """ Class for the events to show in the calendar """
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=255)
    descr = models.TextField(null=True, blank=True)
    start = models.DateTimeField()
    end = models.DateTimeField(null=True, blank=True)
    url = models.URLField(null=True, blank=True)
    typ = models.CharField(max_length=2, choices=EVENT_TYPE,
                           blank=True, null=True)
    venue = models.CharField(max_length=255, null=True, blank=True)
    projects = models.ManyToManyField(Project, related_name='projects')
    as_participant = models.BooleanField(null=True, blank=True)
    # privato
    main_slide_link = models.URLField(null=True, blank=True)
    folder_slides_link = models.URLField(null=True, blank=True)
    report_link = models.URLField(null=True, blank=True)
    image_link = models.URLField(null=True, blank=True)
    folder_image_link = models.URLField(null=True, blank=True)
    registration_link = models.URLField(null=True, blank=True)
    registration_until = models.DateTimeField(null=True, blank=True)
    registration_public = models.BooleanField(
        default=False,
        help_text=_("If true the registration link is public to everyones")
    )
    managers = models.ManyToManyField(User, blank=True)
    program_link = models.URLField(null=True, blank=True)
    program_public = models.BooleanField(
        default=False,
        help_text=_("If true the program link is public to everyones")
    )
    # TODO think if it could be useful
    # logistic_link = models.URLField(null=True, blank=True)

    class Meta:
        db_table = 'event'
        ordering = ['-start']

    def __unicode__(self):
        outstr = f"{self.title}"
        if self.venue:
            outstr += f", {self.venue}"
        outstr += f", {self.start.date()}"
        if self.end:
            outstr += f" / {self.end.date()}"
        return smart_str(outstr)

    def __str__(self):
        return self.__unicode__()

    def natural_key(self):
        return self.__unicode__()


class EventExternal(models.Model):
    """ Class for the events to show in the calendar """
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=255)
    descr = models.TextField(null=True, blank=True)
    start = models.DateTimeField()
    end = models.DateTimeField(null=True, blank=True)
    url = models.URLField(null=True, blank=True)
    typ = models.CharField(max_length=2, choices=EVENT_TYPE,
                           blank=True, null=True)
    venue = models.CharField(max_length=255, null=True, blank=True)
    project = models.ForeignKey(Project, on_delete=models.PROTECT)
    # privato
    main_slide_link = models.URLField(null=True, blank=True)
    participants = models.ManyToManyField(User, blank=True)
    # TODO think if it could be useful
    # logistic_link = models.URLField(null=True, blank=True)

    class Meta:
        db_table = 'event_external'
        ordering = ['-start']

    def __unicode__(self):
        outstr = f"{self.title}"
        if self.venue:
            outstr += f", {self.venue}"
        outstr += f", {self.start.date()}"
        if self.end:
            outstr += f" / {self.end.date()}"
        return smart_str(outstr)

    def __str__(self):
        return self.__unicode__()

    def natural_key(self):
        return self.__unicode__()

pagers/models.py
from django.db import models
from django.utils.encoding import smart_str

from core.models import Project

class Pager(models.Model):
    title = models.CharField(max_length=255)
    date = models.DateField(null=True, blank=True)
    version = models.IntegerField(null=True, blank=True)
    link = models.URLField()
    participant_link = models.URLField(null=True, blank=True)
    external_link = models.URLField(null=True, blank=True)
    active = models.BooleanField(default=True, null=True, blank=True)
    project = models.ManyToManyField(Project)

    class Meta:
        db_table = 'pager'
        ordering = ['title']

    def __unicode__(self):
        return smart_str(f"{self.title}")

    def __str__(self):
        return self.__unicode__()

    def natural_key(self):
        return self.__unicode__()

website/models.py
from django.db import models

# Create your models here.

website/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from captcha.fields import CaptchaField
from core.models import Project

class ContactForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        projects = [(None, "----")]
        for proj in Project.objects.all():
            if proj.name != "EXTERNAL":
                projects.append((proj.id, proj.name))
        self.fields['project'].choices = projects

    contact_name = forms.CharField(
        required=True,
        help_text=_("Your name and surname")
    )
    from_email = forms.EmailField(
        required=True,
        help_text=_("Your e-mail address")
    )
    subject = forms.CharField(
        required=True,
        help_text=_("Subject")
    )
    project = forms.MultipleChoiceField(
        choices=(),
        help_text=_("If you are interested in a specific project please select the one"),
    )
    message = forms.CharField(
        widget=forms.Textarea,
        required=True,
        help_text=_("Message")
    )
    captcha = CaptchaField(help_text=_("Sum 2 and subtract 1 to get the final value"))

events/views.py
from django.shortcuts import render

# Create your views here.

pagers/views.py
from django.shortcuts import render

# Create your views here.

website/views.py
import os
import csv
import json
from datetime import date
from itertools import chain

from django.shortcuts import render
from django.conf import settings
from django.core.mail import send_mail
from django.db.models import Q
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import HttpResponse
from core.models import Project, ResearchGroupProject
from euromammals.functions import is_datacurator
from events.models import Event
from events.models import EventExternal
from publications.models import Publication
from publications.models import PublicationExternal
from pagers.models import Pager

from .forms import ContactForm


def homepage(request):
    """Function to return the home page"""
    today = date.today()
    myevents = Event.objects.filter(start__gt=today).filter(~Q(as_participant=True))[:6]
    reversed_events = sorted(myevents, key=lambda o: o.start)
    pubs = Publication.objects.all()[:6]
    return render(request, template_name="home.html", context={"events": reversed_events, "pubs": pubs})


def contact_view(request):
    """Function for contact"""
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            #form.save()
            tolist = ["euromammals@fmach.it"]
            form_email = form.cleaned_data['from_email']
            if form_email:
                tolist.append(form_email)
            for idstr in form.cleaned_data["project"]:
                try:
                    proj = Project.objects.get(id=int(idstr))
                    tolist.append(f"{proj.name.lower()}.datacurator@fmach.it")
                except Project.DoesNotExist:
                    pass
            email_subject = form.cleaned_data["subject"]
            email_message = f"FROM: {form.cleaned_data['contact_name']}\nEMAIL: {form_email}\nMESSAGE: {form.cleaned_data['message']}"
            if send_mail(email_subject, email_message, settings.EMAIL_HOST_USER, tolist):
                return render(request, 'email_sent.html')
            else:
                return render(request, "500.html")
        else:
            errors = form.errors.keys()
            return render(request, "error.html", {"errs": errors})
    form = ContactForm()
    context = {'form': form}
    return render(request, 'contact.html', context)


def logos(request):
    """Function to return the logos"""
    suffix_dir = os.path.join("img", "logos")
    logodir = os.path.join(settings.STATIC_ROOT, suffix_dir)
    print(logodir)
    mylogos = []
    for root, dirs, files in os.walk(logodir):
        for fil in files:
            mylogos.append(os.path.join(suffix_dir, fil))
    print(logos)
    context = {"logos": mylogos}
    return render(request, 'logos.html', context)


def events(request):
    """Function to return the events"""
    myevents = Event.objects.filter(~Q(as_participant=True))
    projs = Project.objects.all()
    outputs = {}
    for proj in projs:
        outputs[str(proj)] = myevents.filter(projects=proj)
    return render(request, template_name="events.html", context={"items": outputs})


@login_required
def event(request, idd):
    """Function to return page for single event"""
    thisevent = Event.objects.get(id=idd)
    return render(request, template_name="event.html", context={"item": thisevent})


def publications(request):
    """Function to return the publications"""
    publis = Publication.objects.all()
    return render(request, template_name="pubs.html", context={"pubs": publis})


def educational(request):
    """Function to return the educational material"""
    return render(request, template_name="educational.html")


def project(request, projct):
    """Function to return project"""
    try:
        user_projs = request.user.projects.all()
    except:
        user_projs = []
    jsonpath = os.path.join(settings.STATIC_ROOT, "projects", f"{projct.lower()}.json")
    jsonfile = open(jsonpath)
    data = json.load(jsonfile)
    proj = Project.objects.get(name=projct)
    if proj in user_projs:
        proj_template = proj.template_link
        proj_termofuse = proj.termsofuse_link
    else:
        proj_template = None
        proj_termofuse = None
    pubs = Publication.objects.filter(project=proj)
    extpub = PublicationExternal.objects.filter(project=proj)
    events = Event.objects.filter(projects=proj).filter(~Q(as_participant=True))
    participants = EventExternal.objects.filter(project=proj)
    return render(
        request,
        template_name="project.html",
        context={
            "data": data,
            "proj": projct.lower(),
            "pubs": pubs,
            "events": events,
            "external_events": participants,
            "external_pubs": extpub,
            "template": proj_template,
            "termofuse": proj_termofuse
        }
    )

@login_required
def pagers(request):
    """Function to return pagers

    Args:
        request (obj): the request object
    """
    user_projs = request.user.projects.all()
    extproj = Project.objects.filter(name="EXTERNAL")
    mamproj = Project.objects.filter(name="EUROMAMMALS")
    eurocam = Project.objects.filter(name="EUROCAM")
    all_projs = list(chain(user_projs, extproj, mamproj, eurocam))
    mypagers = Pager.objects.filter(project__in=all_projs).distinct()
    outputs = {}
    all = request.GET.get("all", None)
    if not all:
        mypagers = mypagers.filter(active=True)
    for proj in all_projs:
        outputs[str(proj)] = {"pagers": mypagers.filter(project=proj), "url": proj.pager_status}
    return render(
        request,
        template_name="pagers.html",
        context={"items": outputs, "euromammalsurl": mamproj[0].pager_status}
    )

@login_required
def mailing(request):
    """Function to return mailing lists for a user

    Args:
        request (obj): the request object
    """
    user_projs = request.user.projects.all()
    outputs = {}
    for proj in user_projs:
        outputs[str(proj)] = proj.mailing_list
    return render(request, template_name="mailing.html", context={"items": outputs})

@login_required
def database(request):
    """Function to return database info

    Args:
        request (obj): the request object
    """
    return render(request, template_name="database.html")

@user_passes_test(is_datacurator)
def term_of_use(request):
    """Function to return a table with all the information about research groups with their term of use"""
    data = ResearchGroupProject.objects.all()
    format = request.GET.get("format", None)
    if format == "csv":
        response = HttpResponse(content_type="text/csv")
        response["Content-Disposition"] = 'attachment; filename="term_of_use.csv"'
        writer = csv.writer(response)
        writer.writerow(["Research Group", "Project", "Year", "Contact People", "Contact User", "Term of Use"])
        for item in data:
            writer.writerow(
                [
                    item.researchgroup,
                    item.project,
                    item.year,
                    item.contact_people,
                    item.contact_user if item.contact_user else "",
                    item.term_of_use
                ]
            )
        return response
    return render(request, template_name="term_of_use.html", context={"items": data})

website/templates/contact.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
<section class="pt-5 pb-5" id="contact">
    <div class="container">
        <form method="POST" action="." id="insertform">
            {% csrf_token %}
            {{ formset.management_form }}
            <div class="row" id="accordion">
                {% for field in form %}
                <div class="col-12 p-4">
                    {% if field.help_text %}
                    <p class="help small">{{ field.help_text }}</p>
                    {% else %}
                    <p class="help small">{{ field.name}}</p>
                    {% endif %}
                    {{ field.errors }}
                    {% blocktrans %}{{ field }}{% endblocktrans %} 
                </div>
                {% endfor %}
            </div>
            <button type="submit" class="btn btn-primary mr-3">{% trans "Send request" %}</button>
        </form>
    </div>
</section>
{% endblock %}

website/templates/database.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block content %}

<section class="pt-6 pb-7" id="material">
    <div class="container">
        <h2>Database access</h2>
        <div class="row mt-5">
            <div class="col-md-10 mx-auto">
                <p>There are two possibilities to access the database:</p>
                <ul>
                    <li>Via the web using phppgadmin at <a href="https://eurodeer2.fmach.it/phppgadmin/" target="_blank">https://eurodeer2.fmach.it/phppgadmin/</a></li>
                    <li>Using a PostgreSQL client (like DBeaver, pgAdmin, R, Python); the parameters to use are:
                        <ul>
                            <li>Host: eurodeer2.fmach.it</li>
                            <li>Port: 5432</li>
                            <li>Database: DATABASE_YOU_WANT_USE</li>
                            <li>User: YOUR_USER</li>
                            <li>Password: YOUR_PASSWORD</li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</section>
{% endblock %}

website/templates/educational.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block content %}

<section class="pt-6 pb-7" id="material">
    <div class="container">
        <div class="row mt-5">
            <div class="col-md-10 mx-auto">
                <p>We list below educational material prepared for courses and schools organised by EUROMAMMALS, mainly on spatial data management in movement ecology.</p>
                <div class="row text-muted">
                    <div class="col-md">
                        <p>
                            <b><a href="https://github.com/feurbano/data_management_2021" target="_blank">Data Management in Movement Ecology 2021</a></b>
                        </p>
                        <p>
                            <b><a href="https://github.com/feurbano/data_management_2021" target="_blank">Dealing with Spatio-temporal Data in Movement and Population Ecology</a></b>, <em>June 17-22 2018<em> - <em>Trento, Italy</em>
                        </p>
                        <p>
                            <b>SUMMER COURSE: NEXT GENERATION DATA MANAGEMENT IN MOVEMENT ECOLOGY</b>, <em>July 1-10 2015</em> - <em>Trento, Italy</em>
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-md-10 mx-auto pt-4">
                <p>Find also scripts and coding documentation on our <a href="https://github.com/EUROMAMMALS" target="_blank">GitHub repositories <img src="{% static 'img/github-mark.png' %}" class="p-2" width="50px"></a>
            </div>
        </div>
    </div>
</section>
{% endblock %}

website/templates/email_sent.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block content %}
  {% blocktrans %} The email was sent correctly, we will contact you as soon as possible {% endblocktrans %}
{% endblock %}

website/templates/event.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block content %}
<h2 class="text-center text-dark">{{ item.title }}</h2>

{% if item.image_link %}
<p class="pt-2 pb-2"><img src="{{item.image_link}}" width="100%"/><p>
{% endif %}

{% if item.venue %}<h3 class="text-center">{{ item.venue }}</h3>{% endif %}
{% if item.start and item.end %}
<h4 class="text-center">From <b>{{ item.start|date:'Y-m-d' }}</b> to <b>{{ item.end|date:'Y-m-d' }}</b></h4>
{% elif item.start and not item.end %}
<h4 class="text-center"><b>{{ item.start|date:'Y-m-d' }}</b></h4>
{% endif %}

<section class="p-5 section-angle top-right bottom-right" id="sponsor">
    <div class="container">
        <div class="row">
            <div class="col-12 mx-auto text-center">
                {% if item.descr %}
                <p>{{ item.descr|safe }}</p>
                {% endif %}
            </div>
        </div>
        {% if item.url %}
        <a href="{{ item.url }}" target="_blank" class="btn btn-primary mt-2 mb-2">{% trans "Go to main web site" %}</a>
        {% endif %}
        <div class="row">
            <div class="col-12 mx-auto text-center">
                This
                {% if item.typ %}
                {{ item.get_typ_display|lower }}
                {% else %}
                event
                {% endif %}
                is related to
                {% for proj in item.projects.all %}
                 {{ proj }}
                {% endfor %}
            </div>
        </div>
    </div>
</section>

<hr>
{% now "Y-m-d" as today %}
{% if item.registration_until %}
{% if today <= item.registration_until|date:"Y-m-d" %}
<section class="p-5 section-angle top-right bottom-right" id="section-contact">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mx-auto text-center">
                {% trans "If you want to participate" %}
                <br>
                <a href="{{ item.registration_link }}" target="_blank" class="btn btn-primary mt-3">{% trans "Register here" %}</a>
            </div>
        </div>
    </div>
</section>
{% endif %}
{% endif %}

<section class="p-5 section-angle top-right bottom-right" id="section-contact">
    <div class="container">
        <div class="row">
            {% if item.main_slide_link %}
            <div class="col-md-4 mx-auto text-center">
                {% trans "If you look for the main slides" %}
                <br>
                <a href="{{ item.main_slide_link }}" target="_blank" class="btn btn-primary mt-3">{% trans "Download here" %}</a>
            </div>
            {% endif %}
            {% if item.folder_slides_link %}
            <div class="col-md-4 mx-auto text-center">
                {% trans "If you look for all the other slides" %}
                <br>
                <a href="{{ item.folder_slides_link }}" target="_blank" class="btn btn-primary mt-3">{% trans "Download here" %}</a>
            </div>
            {% endif %}
            {% if item.report_link %}
            <div class="col-md-4 mx-auto text-center">
                {% trans "If you look for the report" %}
                <br>
                <a href="{{ item.report_link }}" target="_blank" class="btn btn-primary mt-3">{% trans "Download here" %}</a>
            </div>
            {% endif %}
            {% if item.program_link %}
            <div class="col-md-4 mx-auto text-center">
                {% trans "If you look for the main program" %}
                <br>
                <a href="{{ item.program_link }}" target="_blank" class="btn btn-primary mt-3">{% trans "Download here" %}</a>
            </div>
            {% endif %}
            {% if item.folder_image_link %}
            <div class="col-md-4 mx-auto text-center">
                {% trans "You can see pictures from the event" %}
                <br>
                <a href="{{ item.folder_image_link }}" target="_blank" class="btn btn-primary mt-3">{% trans "See here" %}</a>
            </div>
            {% endif %}
        </div>
    </div>
</section>

{% endblock %}

website/templates/events.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% load filters %}

{% block content %}
{% now "Y-m-d" as today %}
{% for key in PROJECTS_ORDER_LIST %}
    {% with vals=items|getattribute:key %}
    {% if vals|length > 0 %}
    <h3 class="pt-3 text-center">{{ key }}</h3>
    <div class="row">
    {% endif %}
    {% for item in vals %}
        <div class="col-sm-6">
            <div class="card m-2">
                <div class="card-heading">
                    <h4 class="card-title">
                        <a class="btn" data-bs-toggle="collapse" href="#collapseMammals{{item.id}}" role="button" aria-expanded="false" aria-controls="collapseMammals{{ item.id }}">
                            <span class="float-left"><b>{{ item.title }}</b> {% if item.site %}<small>({{ item.site }})</small>{% endif %}</span>
                            <span class="float-right"><i class="fas fa-plus fa-3" id="faicon{{item.id}}"></i></span>
                        </a>
                        {% if request.user.is_staff %}
                        &nbsp;&nbsp;
                        <span><a href="/mammalsadmin/events/event/{{ item.id }}" target="_blank"><i class="fa-solid fa-pen-to-square fa-3" id="editicon{{item.id}}"></i></a></span>
                        {% endif %}
                        {% if request.user.is_authenticated %}
                        &nbsp;&nbsp;
                        <span><a href="/event/{{ item.id }}"><i class="fa-solid fa-right-to-bracket" id="gototevent{{item.id}}"></i></a></span>
                        {% endif %}
                    </h4>
                </div>
                <div id="collapseMammals{{ item.id }}" class="collapse" data-id="{{ item.id }}">
                    <div class="card-body" id="mammals{{ item.id }}">
                        {% if item.venue %}<b>{{ item.venue }}</b>{% endif %}
                        <p>
                        {% if item.start and item.end %}
                        From {{ item.start|date:'Y-m-d' }} to {{ item.end|date:'Y-m-d' }}
                        {% elif item.start and not item.end %}
                        {{ item.start|date:'Y-m-d' }}
                        {% endif %}
                        </p>
                        {% if item.registration_until %}
                        {% if today <= item.registration_until|date:"Y-m-d" %}
                        {% if item.registration_public or request.user.is_authenticated %}
                        <a href="{{ item.registration_link }}" target="_blank" class="btn btn-primary">{% trans "Register here" %}</a>
                        {% endif %}
                        {% endif %}
                        {% endif %}
                        {% if item.program_link %}
                        {% if item.program_public or request.user.is_authenticated %}
                        <a href="{{ item.program_link }}" target="_blank" class="btn btn-primary">{% trans "Program here" %}</a>
                        {% endif %}
                        {% endif %}
                        {% if item.descr %}
                        <p>{{ item.descr|safe }}</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
    {% if vals|length > 0 %}
    </div>
    {% endif %}
    {% endwith %}
{% endfor %}
{% endblock %}

website/templates/logos.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block content %}
{% for logo in logos %}

    <p class="p-4">
        <img src="{% static logo %}" />
    </p>

{% endfor %}
{% endblock %}

website/templates/mailing.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block content %}
    {% if items|length > 0 %}
    <h3 class="pt-3 text-center">Mailing List</h3>
    <div class="row">
    {% for key, vals in items.items %}
        {% if vals is not none %}
        <div class="col-sm-3">
            <a href={{vals}} target="_blank" class="btn btn-primary mt-3">{{key|upper}} mailing list</a>
        </div>
        {% endif %}
    {% endfor %}
    </div>
    {% endif %}
{% endblock %}

website/templates/pagers.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% load filters %}

{% block content %}
Thanks all for contributing to the core of the Euromammals experience, by proposing, leading, working and co-authoring `pagers`, leading to scientific papers!
<br><br>
To boost the recognition of our collaborative work, at the time of publication <b>please remember to number the paper with a unique ID in (approximate) order of publication within each network (here: (*); ask data curators for the order number), and to include the following text in the Acknowledgement section</b>:
<br><br>
This paper was conceived and written within the EUROMAMMALS/EURO’X’ collaborative project (paper no. (*) of the EURO’X’ series; https:// www.eurox.org). The co-authors are grateful to all members of EUROMAMMALS and Vectronic Aerospace GmbH for their support to the initiative. The EUROMAMMALS spatial database is hosted by Fondazione Edmund Mach, Trento, Italy.
<br><br>
Thanks for thinking EUROMAMMALS!

{% for key in PROJECTS_ORDER_LIST %}
    {% with vals=items|getattribute:key %}
    {% if vals != "" %}
    {% if vals.pagers|length > 0 %}
    <h3 class="pt-3 text-center">{{ key }}</h3>
    {% if vals.url %}
        {% if key != "EUROMAMMALS" %}
        <p>For the status of pagers, please see and leave your comments <a href="{{ vals.url }}" target="_blank">here</a></p>
        {% endif %}
    {% endif %}
    {% if euromammalsurl %}
        {% if key == "EUROMAMMALS" %}
        <p>See the status of inter-network pagers and leave your comments <a href="{{ euromammalsurl }}">here</a></p>
        {% endif %}
    {% endif %}
    {% endif %}
    {% for item in vals.pagers %}
    <div class="card">
        <div class="card-heading">
            <h4 class="card-title">
                <a class="btn" data-bs-toggle="collapse" href="#collapseMammals{{item.id}}" role="button" aria-expanded="false" aria-controls="collapseMammals{{ item.id }}">
                    <span class="float-left"><b>{{ item.title }}</b></span>
                    <span class="float-right"><i class="fas fa-plus fa-3" id="faicon{{item.id}}"></i></span>
                </a>
                {% if request.user.is_staff %}
                <a href="/mammalsadmin/pagers/pager/{{ item.id }}" target="_blank" alt="{% translate "Modify pager" %}" title="{% translate "Modify pager" %}">
                    <i class="fa-solid fa-pen-to-square fa-3" id="editicon{{item.id}}"></i>
                </a>
                {% endif %}
            </h4>
        </div>
        <div id="collapseMammals{{ item.id }}" class="collapse" data-id="{{ item.id }}">
            <div class="card-body" id="mammals{{ item.id }}">
                {% if item.active != None %}
                Active: {{ item.active }}
                <br>
                {% endif %}
                <a href="{{item.link}}" target="_blank"><b>Go to the pager</b></a>
                {% if item.participant_link %}
                <br>
                <a href="{{item.participant_link}}" target="_blank"><b>See the participant's list</b></a>
                {% endif %}
                {% if item.external_link %}
                <br>
                <a href="{{item.external_link}}" target="_blank"><b>More info</b></a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}
{% endfor %}
<div id="showButton" class="pt-5"></div>
{% endblock %}

{% block extra_script %}
    <script>
        $(function() {
            const urlObj = new URL(window.location.href);
            var url = urlObj.href;
            var all = urlObj.searchParams.get('all');
            if (all == "true") {
                newurl = url.split("?")[0]
                $("#showButton").text("");
                $("#showButton").append('<a class="btn btn-primary" href="' + newurl +'">Show only active pagers</a>');
            } else {
                newurl = url + "?all=true";
                $("#showButton").text("");
                $("#showButton").append('<a class="btn btn-primary" href="' + newurl +'">Show also not active pagers</a>');
            }
        });

    </script>

{% endblock %}